[2023-08-09T04:29:47.927+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_gcd_etl_basic.download_file_using_BashOperator manual__2023-08-09T04:29:46.755227+00:00 [queued]>
[2023-08-09T04:29:47.938+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_gcd_etl_basic.download_file_using_BashOperator manual__2023-08-09T04:29:46.755227+00:00 [queued]>
[2023-08-09T04:29:47.938+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T04:29:47.952+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): download_file_using_BashOperator> on 2023-08-09 04:29:46.755227+00:00
[2023-08-09T04:29:47.959+0000] {standard_task_runner.py:57} INFO - Started process 1070 to run task
[2023-08-09T04:29:47.963+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_gcd_etl_basic', 'download_file_using_BashOperator', 'manual__2023-08-09T04:29:46.755227+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/example_gcs_upload_download.py', '--cfg-path', '/tmp/tmp7zrwrk6z']
[2023-08-09T04:29:47.965+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask download_file_using_BashOperator
[2023-08-09T04:29:48.021+0000] {task_command.py:410} INFO - Running <TaskInstance: local_gcd_etl_basic.download_file_using_BashOperator manual__2023-08-09T04:29:46.755227+00:00 [running]> on host 738c524d2ce7
[2023-08-09T04:29:48.142+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_gcd_etl_basic' AIRFLOW_CTX_TASK_ID='download_file_using_BashOperator' AIRFLOW_CTX_EXECUTION_DATE='2023-08-09T04:29:46.755227+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-09T04:29:46.755227+00:00'
[2023-08-09T04:29:48.144+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-09T04:29:48.145+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl "https://api.mockaroo.com/api/6872a950?count=1000&key=5f671810" > /resources/mock_users.csv']
[2023-08-09T04:29:48.160+0000] {subprocess.py:86} INFO - Output:
[2023-08-09T04:29:48.163+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /resources/mock_users.csv: No such file or directory
[2023-08-09T04:29:48.163+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-09T04:29:48.180+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-09T04:29:48.186+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=local_gcd_etl_basic, task_id=download_file_using_BashOperator, execution_date=20230809T042946, start_date=20230809T042947, end_date=20230809T042948
[2023-08-09T04:29:48.204+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 60 for task download_file_using_BashOperator (Bash command failed. The command returned a non-zero exit code 1.; 1070)
[2023-08-09T04:29:48.254+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-09T04:29:48.301+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
